### ISSUE TITLE
Name collision

### ISSUE THREAD

**Issue by fnc12** [godexsoft/sqlite_orm#2]
Hello there. I got a C++ sqlite3 wrapper lib called `sqlite_orm` too and located [here](https://github.com/fnc12/sqlite_orm). What do you think about name collision? Maybe it would be better if you change the name? Thanks

**Comment by godexsoft** [comment]
Hi,

Considering my lib is like 3-4 years older than yours i can only suggest you change the name of yours ;)
However I don't care about my orm much even tho it is actually used by some people. It's outdated and not supported for years. I don't see a problem or any name clash as let's face it both libraries are thrash and will never become popular.

With best regards,
Alex

**Comment by fnc12** [comment]
Ok. Nice. Thanks
